// <auto-generated />
using System;
using AkordideApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkordideApi.Migrations
{
    [DbContext(typeof(AkordContext))]
    [Migration("20251127124401_init9")]
    partial class init9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AkordideApi.Models.Kolmkola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Pohitoon")
                        .HasColumnType("int");

                    b.Property<string>("Tahis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tyypp")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Kolmkolad");

                    b.HasDiscriminator<string>("Tyypp").HasValue("Kolmkola");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AkordideApi.Models.Lugu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nimetus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lood");
                });

            modelBuilder.Entity("AkordideApi.Models.Takt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KolmkolaId")
                        .HasColumnType("int");

                    b.Property<int?>("KolmkolaId1")
                        .HasColumnType("int");

                    b.Property<int?>("LuguId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KolmkolaId");

                    b.HasIndex("KolmkolaId1");

                    b.HasIndex("LuguId");

                    b.ToTable("Taktid");
                });

            modelBuilder.Entity("AkordideApi.Models.CKolmkola", b =>
                {
                    b.HasBaseType("AkordideApi.Models.Kolmkola");

                    b.HasDiscriminator().HasValue("C");
                });

            modelBuilder.Entity("AkordideApi.Models.FKolmkola", b =>
                {
                    b.HasBaseType("AkordideApi.Models.Kolmkola");

                    b.HasDiscriminator().HasValue("F");
                });

            modelBuilder.Entity("AkordideApi.Models.GKolmkola", b =>
                {
                    b.HasBaseType("AkordideApi.Models.Kolmkola");

                    b.HasDiscriminator().HasValue("G");
                });

            modelBuilder.Entity("AkordideApi.Models.Takt", b =>
                {
                    b.HasOne("AkordideApi.Models.Kolmkola", "Kolmkola")
                        .WithMany()
                        .HasForeignKey("KolmkolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AkordideApi.Models.Kolmkola", null)
                        .WithMany("Taktid")
                        .HasForeignKey("KolmkolaId1");

                    b.HasOne("AkordideApi.Models.Lugu", null)
                        .WithMany("Taktid")
                        .HasForeignKey("LuguId");

                    b.Navigation("Kolmkola");
                });

            modelBuilder.Entity("AkordideApi.Models.Kolmkola", b =>
                {
                    b.Navigation("Taktid");
                });

            modelBuilder.Entity("AkordideApi.Models.Lugu", b =>
                {
                    b.Navigation("Taktid");
                });
#pragma warning restore 612, 618
        }
    }
}
